# Generated by Django 3.1.1 on 2020-10-12 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstUI', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Countries',
            new_name='Country',
        ),
    ]
