# Generated by Django 3.1.1 on 2020-10-12 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstUI', '0002_auto_20201012_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='default_hist',
            field=models.BooleanField(),
        ),
    ]
