# Generated by Django 3.1.1 on 2020-10-12 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstUI', '0003_auto_20201012_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
