# Generated by Django 3.1.1 on 2020-10-12 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstUI', '0006_auto_20201012_0904'),
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstUI.country')),
            ],
        ),
    ]
