# Generated by Django 3.1.1 on 2020-10-12 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstUI', '0007_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='data',
            new_name='FinanceData',
        ),
    ]
