# Generated by Django 3.1.1 on 2020-10-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstUI', '0008_auto_20201012_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='financedata',
            name='lastUpdate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='financedata',
            name='year',
            field=models.IntegerField(default=2019),
        ),
    ]
