# Generated by Django 3.1.1 on 2020-10-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstUI', '0010_auto_20201012_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='financedata',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
