# Generated by Django 3.1.1 on 2020-10-12 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstUI', '0011_financedata_show'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financedata',
            old_name='year',
            new_name='data_year',
        ),
    ]
