# Generated by Django 3.1.1 on 2020-10-12 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstUI', '0012_auto_20201012_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financedata',
            name='Speculative_Grade_Prob',
            field=models.FloatField(default=None, null=True),
        ),
    ]
