# Generated by Django 3.1.1 on 2020-10-12 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstUI', '0013_auto_20201012_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financedata',
            name='log_real_gnipc',
            field=models.FloatField(default=None, null=True),
        ),
    ]
