# Generated by Django 3.1.1 on 2020-10-12 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstUI', '0015_auto_20201012_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financedata',
            name='country_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstUI.country', unique=True),
        ),
        migrations.AlterField(
            model_name='financedata',
            name='data_year',
            field=models.IntegerField(default=2019, unique=True),
        ),
    ]
